### ISSUE TITLE
Underscore and LoDash Dependencies

### ISSUE THREAD

**Issue by mrtnbroder** [kjda/ReactFlux#10]
May I ask why both are required? They are pretty much the same.

Would be awesome if you could stick to LoDash only and upgrade it to the latest version!

**Comment by lelandrichardson** [comment]
+1

I think sticking to LoDash and pulling out just the methods needed (since it's using commonJS) is ideal

**Comment by kjda** [comment]
Underscore Template was used for code generation.. yea, but lodash has it as well.. so fixed.. thanks!
