### ISSUE TITLE
Callback for setState

### ISSUE THREAD

**Issue by LKay** [kjda/ReactFlux#12]
I think ``setState`` should be consistent with native React method and accept callback as last parameter. for now it's difficult to handle multiple actions called from the same place.

**Comment by lelandrichardson** [comment]
In general I like being consistent with React, but I think the situation may be different here. The callback in React is for you to do something after the component is re-rendered as a result of the state change (which is an asynchronous thing).

In this case I'm pretty sure setting state is simply updating an immutable object, which is a synchronous action.

**Comment by kjda** [comment]
good point Leland..

**Comment by LKay** [comment]
Fair enough.
