### ISSUE TITLE
success event never dispatched again after an Exception is thrown during an ActionHandler success callback

### ISSUE THREAD

**Issue by ecstasy2** [kjda/ReactFlux#14]
I have the following ActionHandler

    Store.addActionHandler(constants.SAVE_GROUP, {
	
	getInitialState: function(){
		return {
			isSaving: false,
			group: {}
		};
	},

	before: function(){
		this.setState({
			isSaving: true
		});
	},

	success: function(resp){
		this.setState({
			isSaving: false,
			saved: true,
		});

		var groups = this.parent.get('groups');
		groups.push(resp);
	},

	fail: function(resp){
		this.setState({
			isSaving: false,
			error: resp,
		});
	},

	after: function(){
		debugger
	}

});

The line groups.push(resp); in the success callback throw an error sometime due to the 'resp' being undefined.

The first problem is that somehow ReactFlux catch this Exception and doesn't log it anywhere. Which mean you will spend a lot of time stepping through your code before finding a potential bug.

The second Bug is that Success event is never dispatched again after the first failure. the After event get dispatched though.

**Comment by kjda** [comment]
I'll look at this asap

**Comment by LKay** [comment]
I have similar problem and looks like it needs fixing as well. I have a jQuery ajax promise returned in the action and let's say `ACTION` constant. For the first time the ajax requests fails and both `ACTION` and `ACTION_FAIL` constant trigger proper methods. But If I try to call the action again only `ACTION` gets triggered and none of the `ACTION_FAIL`, `ACTION_SUCCESS` or `ACTION_AFTER` gets called for the second time. I have to refresh the page. Tried to debug it but looks like some exceptions are maybe muted. This might be related to this issue.
