### ISSUE TITLE
Allow as mixin

### ISSUE THREAD

**Issue by mrtnbroder** [kjda/ReactFlux#15]
I'm refactoring some of my components right now to keep stuff DRY, and I noticed this:

```
Uncaught Error: Invariant Violation: ReactCompositeComponentInterface: You are attempting to define `getStateFromStores` on your component more than once. This conflict may be due to a mixin.
```

I'm requiring state from a react-flux store in my mixin, and some other state in my component. Would it be possible to get both compatible? Not sure if a new method for this is needed, such as `getStateFromStoresInMixins` or something.

**Comment by kjda** [comment]
I think this happens if two mixins try to inject the same method on a react component... what about adding a proxy to getStateFromStores --> i.e  getStateFromReactFlux

**Comment by mrtnbroder** [comment]
that looks kinda hacki-ish. Wouldn't it make sense to keep it the way facebook does it and merge these methods? I think it makes sense.

**Comment by kjda** [comment]
ok. I think I misunderstood the problem. Somehow, I thought you are using extra library that has getStateFromStores

so you have something like this
```
var mixin1 = {
  getStateFromStores: function(){....}
}

var mixin2 = {
  getStateFromStores: function(){....}
}

var component = React.createComponent({
   mixins: [mixin1, mixin2]
})
```
Well, this has nothing to do with ReactFlux, it is react specefic

to solve this don't use getStateFromStores in those mixins but use store.onChange and store.offChange methods on componentDid/WillMount and componentWillUnmount respectively

**Comment by mrtnbroder** [comment]
I see. Ok that should fix the problem.

my example actually looks more like this:

```
var mixin1 = {
  getStateFromStores: function(){....}
}

var component = React.createComponent({
   mixins: [mixin1],

  getStateFromStores: function(){....}
})
```

I guess we can close this issue then.

Keep up the good work man! Love this library.
