### ISSUE TITLE
Use alternate promise library that is compatible with React Native

### ISSUE THREAD

**Issue by lelandrichardson** [kjda/ReactFlux#24]
I just started playing around with React Native, and wanted to use this library with it.

The promise library that's referenced with this library ends up using the `process` environment variable, which isn't available in React Native.  I was essentially able to get everything working by just commenting out the `require('promise')` calls in this library (since there is a global `Promise` defined in the React Native environment).

One approach could be to just replace

```
var Promise = require('promise');
```

with

```
Promise = Promise || require('promise');
```

or something like that.

What are your thoughts?  This is just a suggestion...

**Comment by kjda** [comment]
Hi Leland, this looks good. Some browsers have native Promise support as well, so it would be helpful. any suggestion for a library that supports this already? otherwise, I can implement your suggestion.

**Comment by lelandrichardson** [comment]
I'm not really sure. Since there are a lot of promise libraries out there, some of which are natively available in browsers and other environments, it seems like the best long-term strategy is to turn Promise into a "polyfill" type dependency, where you just instruct those who are using the library to have a polyfilled `Promise` constructor available or else the library won't work. This would be a breaking change for many (but a pretty easy fix at least). Would be similar in spirit to how React requires an ES5 polyfill library.

The benefit then is that the weight of the promise library no longer needs to be included in the payload of ReactFlux, especially if the developer is already using another promise library somewhere else.

Thoughts?

**Comment by kjda** [comment]
fixed using: Promise = Promise || require('promise');
in a future major release I will remove promise hard-dependency
